name: backquest
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+29

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  

  video_player: ^2.9.5
  chewie: ^1.11.3
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.1.3
  stroke_text: ^0.0.2
  flutter_neumorphic: ^3.2.0
  google_fonts: ^6.2.1
  quickalert: ^1.1.0
  audioplayers: ^6.1.2
  lottie: ^3.2.0
  get_it: ^8.0.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.1.0
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  path_provider: ^2.1.5
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.4.0
  in_app_purchase_storekit: ^0.3.22+1

dev_dependencies:

  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/playstorelogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/playstorelogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/playstorelogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/playstorelogo.png"

  flutter_lints: ^4.0.0    

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/playstorelogo.png
    - assets/settingsbg.PNG
    - assets/thumbnails/
    - assets/gifs/