// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtktBbO7sGsuU2IzVn7PvtEwXY2uC4bgE',
    appId: '1:31068949391:web:08202d297cfdaab39e59fa',
    messagingSenderId: '31068949391',
    projectId: 'langobattle',
    authDomain: 'langobattle.firebaseapp.com',
    storageBucket: 'langobattle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuSCHrsJ64T0jKaem3q7ekDDTgCR_NWKw',
    appId: '1:31068949391:android:7385fe318f58a9229e59fa',
    messagingSenderId: '31068949391',
    projectId: 'langobattle',
    storageBucket: 'langobattle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Mlw2ZjeSYf_rJ5VyqLjJBvsq1DzUNC4',
    appId: '1:31068949391:ios:83a40737aab254ff9e59fa',
    messagingSenderId: '31068949391',
    projectId: 'langobattle',
    storageBucket: 'langobattle.firebasestorage.app',
    iosBundleId: 'com.tgeiling.langobattle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Mlw2ZjeSYf_rJ5VyqLjJBvsq1DzUNC4',
    appId: '1:31068949391:ios:8e14e0db2f65f9969e59fa',
    messagingSenderId: '31068949391',
    projectId: 'langobattle',
    storageBucket: 'langobattle.firebasestorage.app',
    iosBundleId: 'com.tgeiling.lingobattle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtktBbO7sGsuU2IzVn7PvtEwXY2uC4bgE',
    appId: '1:31068949391:web:b7379e93be386a949e59fa',
    messagingSenderId: '31068949391',
    projectId: 'langobattle',
    authDomain: 'langobattle.firebaseapp.com',
    storageBucket: 'langobattle.firebasestorage.app',
  );
}
